import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import { AppBar, Box, Container, Grid2, Toolbar, Typography } from "@mui/material";
import "./globals.css";
import Image from "next/image";
import logo from '@/../public/logo-masa-round.svg'

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
 
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={roboto.variable}>
        <ThemeProvider theme={theme}>
          
          <div style={{ position: 'absolute', width: '100%' }}>
            <Container maxWidth="md">
              <Toolbar>
                <Image src={logo} alt='' width={120} style={{ marginLeft: '-80px' }}></Image>
              </Toolbar>
            </Container>
          </div>
          
          <AppRouterCacheProvider options={{ key: 'css' }}>
            <Container maxWidth="md">
              <NextIntlClientProvider messages={messages}>
                {children}
              </NextIntlClientProvider>
            </Container>    
          </AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
